apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: YWRpdHlhLW1vbmdv   # base64 for "aditye-username"
  mongo-root-password: YWRpdHlhLXBhc3N3b3Jk   # base64 for "adityapassword"
